module.exports = {
    publicPath: './',
    productionSourceMap: false,
}

/*
[{
    "id": 47,
    "zhangfu": "-5.374",
    "code": "601601",
    "name": "中国太保",
    "jijin": ["中欧股票全明星合", "交银带飞组合"],
    "hangye1": "保险",
    "hangye2": "金融业-保险业",
    "shichang": "上海证券交易所"
}, {
    "id": 36,
    "zhangfu": "-2.274",
    "code": "601318",
    "name": "中国平安",
    "jijin": ["交银带飞组合", "中欧股票全明星合"],
    "hangye1": "保险",
    "hangye2": "金融业-保险业",
    "shichang": "上海证券交易所"
}, {
    "id": 30,
    "zhangfu": "-4.834",
    "code": "000733",
    "name": "振华科技",
    "jijin": ["交银带飞组合", "长信国防军工量化混合C"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 16,
    "zhangfu": "-4.269",
    "code": "300750",
    "name": "宁德时代",
    "jijin": ["中欧股票全明星合", "交银带飞组合"],
    "hangye1": "汽车行业",
    "hangye2": "制造业-电气机械和器材制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 11,
    "zhangfu": "1.863",
    "code": "002352",
    "name": "顺丰控股",
    "jijin": ["中欧股票全明星合", "交银带飞组合"],
    "hangye1": "交运物流",
    "hangye2": "交通运输、仓储和邮政业-邮政业",
    "shichang": "深圳证券交易所"
}, {
    "id": 59,
    "zhangfu": "",
    "code": "HKOOGL",
    "name": "谷歌A",
    "jijin": ["交银环球精选混合(QDII)"]
}, {
    "id": 58,
    "zhangfu": "-1.042",
    "code": "ASML NA",
    "name": "阿斯麦控股公司",
    "jijin": ["交银环球精选混合(QDII)"]
}, {
    "id": 57,
    "zhangfu": "-0.281",
    "code": "AMZN",
    "name": "亚马逊",
    "jijin": ["交银环球精选混合(QDII)"]
}, {
    "id": 56,
    "zhangfu": "-4.142",
    "code": "HK2333",
    "name": "长城汽车",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "汽车",
    "shichang": "香港交易所"
}, {
    "id": 55,
    "zhangfu": "1.678",
    "code": "HK2269",
    "name": "药明生物",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "药品及生物科技",
    "shichang": "香港交易所"
}, {
    "id": 54,
    "zhangfu": "2.150",
    "code": "HK2020",
    "name": "安踏体育",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "纺织及服饰",
    "shichang": "香港交易所"
}, {
    "id": 53,
    "zhangfu": "-6.661",
    "code": "HK1772",
    "name": "赣锋锂业",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "一般金属及矿石",
    "shichang": "香港交易所"
}, {
    "id": 52,
    "zhangfu": "-0.871",
    "code": "HK0881",
    "name": "中升控股",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "专业零售",
    "shichang": "香港交易所"
}, {
    "id": 51,
    "zhangfu": "0.073",
    "code": "HK0700",
    "name": "腾讯控股",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "软件服务",
    "shichang": "香港交易所"
}, {
    "id": 50,
    "zhangfu": "1.935",
    "code": "HK0291",
    "name": "华润啤酒",
    "jijin": ["交银环球精选混合(QDII)"],
    "hangye1": "食物饮品",
    "shichang": "香港交易所"
}, {
    "id": 49,
    "zhangfu": "4.034",
    "code": "603008",
    "name": "喜临门",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "木业家具",
    "hangye2": "制造业-家具制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 48,
    "zhangfu": "-1.211",
    "code": "601965",
    "name": "中国汽研",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "汽车行业",
    "hangye2": "科学研究和技术服务业-专业技术服务业",
    "shichang": "上海证券交易所"
}, {
    "id": 46,
    "zhangfu": "-2.932",
    "code": "601336",
    "name": "新华保险",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "保险",
    "hangye2": "金融业-保险业",
    "shichang": "上海证券交易所"
}, {
    "id": 45,
    "zhangfu": "-4.247",
    "code": "600297",
    "name": "广汇汽车",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "汽车行业",
    "hangye2": "批发和零售业-零售业",
    "shichang": "上海证券交易所"
}, {
    "id": 44,
    "zhangfu": "0.273",
    "code": "002327",
    "name": "富安娜",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "纺织服装",
    "hangye2": "制造业-纺织业",
    "shichang": "深圳证券交易所"
}, {
    "id": 43,
    "zhangfu": "0.459",
    "code": "002048",
    "name": "宁波华翔",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "汽车行业",
    "hangye2": "制造业-汽车制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 42,
    "zhangfu": "1.154",
    "code": "002035",
    "name": "华帝股份",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "家电行业",
    "hangye2": "制造业-电气机械和器材制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 41,
    "zhangfu": "-2.791",
    "code": "000910",
    "name": "大亚圣象",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "木业家具",
    "hangye2": "制造业-木材加工及木、竹、藤、棕、草制品业",
    "shichang": "深圳证券交易所"
}, {
    "id": 40,
    "zhangfu": "-1.728",
    "code": "000651",
    "name": "格力电器",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "家电行业",
    "hangye2": "制造业-电气机械和器材制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 39,
    "zhangfu": "-8.240",
    "code": "603678",
    "name": "火炬电子",
    "jijin": ["交银带飞组合"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 38,
    "zhangfu": "-5.670",
    "code": "603267",
    "name": "鸿远电子",
    "jijin": ["交银带飞组合"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 35,
    "zhangfu": "-3.571",
    "code": "601137",
    "name": "博威合金",
    "jijin": ["交银带飞组合"],
    "hangye1": "有色金属",
    "hangye2": "制造业-有色金属冶炼和压延加工业",
    "shichang": "上海证券交易所"
}, {
    "id": 34,
    "zhangfu": "-1.089",
    "code": "300408",
    "name": "三环集团",
    "jijin": ["交银带飞组合"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 33,
    "zhangfu": "-2.294",
    "code": "300014",
    "name": "亿纬锂能",
    "jijin": ["交银带飞组合"],
    "hangye1": "电子元件",
    "hangye2": "制造业-电气机械和器材制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 32,
    "zhangfu": "5.145",
    "code": "002928",
    "name": "华夏航空",
    "jijin": ["交银带飞组合"],
    "hangye1": "民航机场",
    "hangye2": "交通运输、仓储和邮政业-航空运输业",
    "shichang": "深圳证券交易所"
}, {
    "id": 31,
    "zhangfu": "-1.024",
    "code": "002049",
    "name": "紫光国微",
    "jijin": ["交银带飞组合"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 29,
    "zhangfu": "-2.863",
    "code": "600372",
    "name": "中航电子",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "航天航空",
    "hangye2": "制造业-铁路、船舶、航空航天和其他运输设备制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 28,
    "zhangfu": "-4.338",
    "code": "600038",
    "name": "中直股份",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "航天航空",
    "hangye2": "制造业-铁路、船舶、航空航天和其他运输设备制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 27,
    "zhangfu": "-1.437",
    "code": "300762",
    "name": "上海瀚讯",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "通讯行业",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 26,
    "zhangfu": "0.249",
    "code": "300699",
    "name": "光威复材",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "化工行业",
    "hangye2": "制造业-化学纤维制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 25,
    "zhangfu": "-3.050",
    "code": "300696",
    "name": "爱乐达",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "航天航空",
    "hangye2": "制造业-铁路、船舶、航空航天和其他运输设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 24,
    "zhangfu": "-3.931",
    "code": "300474",
    "name": "景嘉微",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "航天航空",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 23,
    "zhangfu": "-4.311",
    "code": "002829",
    "name": "星网宇达",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "电子信息",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 22,
    "zhangfu": "-2.211",
    "code": "002465",
    "name": "海格通信",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "通讯行业",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 21,
    "zhangfu": "-1.711",
    "code": "002179",
    "name": "中航光电",
    "jijin": ["长信国防军工量化混合C"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 18,
    "zhangfu": "-0.338",
    "code": "600660",
    "name": "福耀玻璃",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "玻璃陶瓷",
    "hangye2": "制造业-非金属矿物制品业",
    "shichang": "上海证券交易所"
}, {
    "id": 17,
    "zhangfu": "0.386",
    "code": "600309",
    "name": "万华化学",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "化工行业",
    "hangye2": "制造业-化学原料及化学制品制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 15,
    "zhangfu": "4.451",
    "code": "300454",
    "name": "深信服",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "软件服务",
    "hangye2": "信息传输、软件和信息技术服务业-软件和信息技术服务业",
    "shichang": "深圳证券交易所"
}, {
    "id": 14,
    "zhangfu": "0.784",
    "code": "300124",
    "name": "汇川技术",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "仪器仪表",
    "hangye2": "制造业-电气机械和器材制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 13,
    "zhangfu": "-7.376",
    "code": "002460",
    "name": "赣锋锂业",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "有色金属",
    "hangye2": "制造业-有色金属冶炼和压延加工业",
    "shichang": "深圳证券交易所"
}, {
    "id": 12,
    "zhangfu": "-1.486",
    "code": "002415",
    "name": "海康威视",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "安防设备",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 10,
    "zhangfu": "1.905",
    "code": "002311",
    "name": "海大集团",
    "jijin": ["中欧股票全明星合"],
    "hangye1": "农牧饲渔",
    "hangye2": "制造业-农副食品加工业",
    "shichang": "深圳证券交易所"
}, {
    "id": 9,
    "zhangfu": "-0.769",
    "code": "603816",
    "name": "顾家家居",
    "jijin": ["交银带飞组合"],
    "hangye1": "木业家具",
    "hangye2": "制造业-家具制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 8,
    "zhangfu": "0.812",
    "code": "603259",
    "name": "药明康德",
    "jijin": ["交银带飞组合"],
    "hangye1": "医疗行业",
    "hangye2": "科学研究和技术服务业-研究和试验发展",
    "shichang": "上海证券交易所"
}, {
    "id": 7,
    "zhangfu": "1.350",
    "code": "600519",
    "name": "贵州茅台",
    "jijin": ["交银带飞组合"],
    "hangye1": "酿酒行业",
    "hangye2": "制造业-酒、饮料和精制茶制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 6,
    "zhangfu": "1.446",
    "code": "600346",
    "name": "恒力石化",
    "jijin": ["交银带飞组合"],
    "hangye1": "化纤行业",
    "hangye2": "制造业-化学纤维制造业",
    "shichang": "上海证券交易所"
}, {
    "id": 4,
    "zhangfu": "5.462",
    "code": "002475",
    "name": "立讯精密",
    "jijin": ["交银带飞组合"],
    "hangye1": "电子元件",
    "hangye2": "制造业-计算机、通信和其他电子设备制造业",
    "shichang": "深圳证券交易所"
}, {
    "id": 2,
    "zhangfu": "1.677",
    "code": "002271",
    "name": "东方雨虹",
    "jijin": ["交银带飞组合"],
    "hangye1": "水泥建材",
    "hangye2": "制造业-非金属矿物制品业",
    "shichang": "深圳证券交易所"
}]


*/